;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        company-complete
        delete-horizontal-space
        fix-word-capitalize
        fix-word-upcase
        helm-M-x
        indent-for-tab-command
        join-next-line
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-ctrl-c-minus
        org-delete-char
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        dired-jump
        mouse-set-region
        save-all
        split-window-below-focus
        ))
