;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-visual-line
        company-complete
        delete-horizontal-space
        drag-stuff-up
        fix-word-capitalize
        fix-word-downcase
        fix-word-upcase
        helm-M-x
        indent-for-tab-command
        join-next-line
        markdown-outdent-or-delete
        org-beginning-of-line
        org-ctrl-c-ctrl-c
        org-ctrl-c-minus
        org-ctrl-c-star
        org-cycle
        org-delete-char
        org-self-insert-command
        wdired--self-insert
        ))

(setq mc/cmds-to-run-once
      '(
        dired-jump
        end-of-buffer
        magit-stage
        magit-status
        mouse-set-region
        save-all
        smart-jump-go
        split-window-below-focus
        ))
